-- Criar tabela de membros
create table membros (
  id bigint generated by default as identity primary key,
  nome text not null,
  cor text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar tabela de transações
create table transacoes (
  id bigint generated by default as identity primary key,
  tipo text not null, -- 'income' ou 'expense'
  valor decimal not null,
  descricao text not null,
  data date not null,
  categoria text not null,
  icone text,
  membro_id bigint references membros(id),
  recorrencia text default 'once',
  status text default 'paid',
  data_vencimento date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar tabela de metas
create table metas (
  id bigint generated by default as identity primary key,
  nome text not null,
  valor_alvo decimal not null,
  valor_atual decimal default 0,
  prazo date,
  icone text,
  cor text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ativar RLS (Row Level Security) - Importante para segurança
alter table membros enable row level security;
alter table transacoes enable row level security;
alter table metas enable row level security;

-- Criar políticas simples para permitir leitura/escrita (ajuste conforme necessário para produção)
create policy "Public access" on membros for all using (true);
create policy "Public access" on transacoes for all using (true);
create policy "Public access" on metas for all using (true);
